# Generated by Django 5.2.8 on 2025-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='شرکت')),
                ('service_type', models.CharField(choices=[('maquette', 'ماکت\u200cسازی'), ('consulting', 'مشاوره'), ('shipping', 'ارسال بین\u200cالمللی'), ('design', 'طراحی'), ('other', 'سایر')], max_length=50, verbose_name='نوع خدمات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_review', 'در حال بررسی'), ('contacted', 'تماس گرفته شده'), ('quoted', 'پیش\u200cفاکتور ارسال شده'), ('closed', 'بسته شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست مشتری',
                'verbose_name_plural': 'درخواست\u200cهای مشتریان',
                'ordering': ['-created_at'],
            },
        ),
    ]
