# Generated by Django 5.2.8 on 2025-11-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('in_review', 'در حال بررسی'), ('contacted', 'تماس گرفته شده'), ('quoted', 'پیش \u200cفاکتور ارسال شده'), ('closed', 'بسته شده')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
    ]
