# Generated by Django 5.2.8 on 2025-12-06 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('finished', 'تکمیل شده'), ('in_progress', 'در حال اجرا'), ('planned', 'برنامه\u200cریزی شده')], default='completed', max_length=20, verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/main/', verbose_name='تصویر')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='نام کارفرما')),
                ('project_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پروژه')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='موقعیت')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='مدت زمان اجرا')),
                ('scale', models.CharField(blank=True, max_length=50, verbose_name='مقیاس')),
                ('materials', models.TextField(blank=True, verbose_name='مواد به کار رفته')),
                ('special_features', models.TextField(blank=True, verbose_name='ویژگی\u200cهای خاص')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پروژه ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'تصاویر پروژه',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
