# Generated by Django 5.2.8 on 2025-11-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='محتوای مقاله')),
                ('summary', models.TextField(max_length=500, verbose_name='خلاصه مقاله')),
                ('cover_image', models.ImageField(upload_to='blog/covers/', verbose_name='تصویر کاور')),
                ('category', models.CharField(choices=[('industrial_maquette', 'ماکت صنعتی'), ('petrochemical', 'پتروشیمی'), ('oil_gas', 'نفت و گاز'), ('steel', 'فولاد'), ('technology', 'تکنولوژی'), ('tips', 'نکات فنی')], max_length=50, verbose_name='دسته\u200cبندی')),
                ('author', models.CharField(default='تیم پرتو تجسم', max_length=100, verbose_name='نویسنده')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقاله ویژه')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('author_email', models.EmailField(max_length=254, verbose_name='ایمیل نویسنده')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveIntegerField(choices=[(1, '۱ ستاره'), (2, '۲ ستاره'), (3, '۳ ستاره'), (4, '۴ ستاره'), (5, '۵ ستاره')], default=5, verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_spam', models.BooleanField(default=False, verbose_name='اسپم')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
    ]
