# Generated by Django 5.2.8 on 2025-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('petrochemical', 'پتروشیمی'), ('oil', 'نفت'), ('atomic energy', 'گاز'), ('steel', 'فولاد'), ('pharmaceutical', 'صنعتی'), ('construction', 'ساختمانی'), ('road construction', 'ساخت و ساز جاده'), ('urban development', 'توسعه شهری'), ('other', 'غیره'), ('tips', 'نکات فنی')], max_length=50, verbose_name='دسته\u200cبندی'),
        ),
    ]
