# Generated by Django 5.2.8 on 2025-11-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_summary_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('petrochemical', 'پتروشیمی'), ('oil', 'نفت'), ('atomic energy', 'گاز'), ('steel', 'فولاد'), ('pharmaceutical', 'صنعتی'), ('construction', 'ساختمانی'), ('road construction', 'ساخت و ساز جاده'), ('urban development', 'توسعه شهری'), ('other', 'غیره')], max_length=50, verbose_name='دسته\u200cبندی'),
        ),
    ]
