# Generated by Django 5.2.8 on 2025-11-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='لوگو')),
                ('website', models.URLField(blank=True, verbose_name='وبسایت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('description', models.TextField(verbose_name='توضیحات شرکت')),
                ('mission', models.TextField(blank=True, verbose_name='ماموریت')),
                ('vision', models.TextField(blank=True, verbose_name='چشم\u200cانداز')),
                ('values', models.TextField(blank=True, verbose_name='ارزش\u200cها')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='سال تجربه')),
                ('completed_projects', models.PositiveIntegerField(default=0, verbose_name='پروژه\u200cهای تکمیل شده')),
                ('happy_clients', models.PositiveIntegerField(default=0, verbose_name='مشتریان راضی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات شرکت',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(upload_to='team/', verbose_name='تصویر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
