# Generated by Django 5.2.8 on 2025-11-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_client_companyinfo_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('working_hours', models.TextField(verbose_name='ساعات کاری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
    ]
